export interface ItemModel {
  id?: number;
  itemId: string;
  warehouseId: number;
  clientId: number;
  orderId: number;
  itemType: string;
  status: string;
  statusName?: string;
  quantity: number;
  deletedBy?: string;
  deletedCause?: string;
  deletedDatetime?: string;
  observations?: string;
  imageFilename?: string;
  contentFilename?: string;
  manufacter?: string;
  model?: string;
  partNumber?: string;
  serialNumber?: string;
  uaNumber?: string;
  condition: string;
  conditionName?: string;
  unitLength?: string;
  width?: number | 0;
  height?: number | 0;
  length?: number | 0;
  unitWeight?: string;
  weight?: number | 0;
  unitVolume?: string;
  volumeWeight?: number | 0;
}
